Repository oSoc18/Octotrails, pull requests merged in 2018-07, with the labels that each got.

#49 Changed tech_id to stop_id
  src/web-api/controllers/stops.controller.js
Labels: backend, fix

#51 Feature/38 get proximity api
  src/web-api/controllers/stops.controller.js
  src/web-api/routes/stops.route.js
Labels: api, backend

#52 Feature/seed empty mongo collections
  .env
  src/web-api/index.js
  src/web-api/models/seeds/index.js
  src/web-api/models/seeds/questions.mock.json
  src/web-api/models/seeds/questions.seed.js
Labels: api

#53 Remove console log
  src/web-api/models/seeds/questions.seed.js
Labels: fix

#54 Update .env
  .env
Labels: fix

#59 Fix/remove sample codes
  src/web-api/controllers/heroes.controller.js
  src/web-api/controllers/lines.controller.js
  src/web-api/models/hero.model.js
  src/web-api/models/line.model.js
  src/web-api/routes/heroes.route.js
  src/web-api/routes/index.route.js
  src/web-api/routes/lines.route.js
  src/web-app/app/app.module.ts
  src/web-app/app/heroes/dashboard/hero-dashboard.component.html
  src/web-app/app/heroes/dashboard/hero-dashboard.component.scss
  src/web-app/app/heroes/dashboard/hero-dashboard.component.spec.ts
  src/web-app/app/heroes/dashboard/hero-dashboard.component.ts
  src/web-app/app/heroes/detail/hero-detail.component.html
  src/web-app/app/heroes/detail/hero-detail.component.scss
  src/web-app/app/heroes/detail/hero-detail.component.spec.ts
  src/web-app/app/heroes/detail/hero-detail.component.ts
  src/web-app/app/heroes/hero.service.ts
  src/web-app/app/heroes/hero.ts
  src/web-app/app/heroes/heroes-routing.module.ts
  src/web-app/app/heroes/heroes.component.ts
  src/web-app/app/heroes/heroes.mock.ts
  src/web-app/app/heroes/heroes.module.ts
  src/web-app/app/heroes/list/hero-list.component.html
  src/web-app/app/heroes/list/hero-list.component.scss
  src/web-app/app/heroes/list/hero-list.component.spec.ts
  src/web-app/app/heroes/list/hero-list.component.ts
  src/web-app/app/heroes/search/hero-search.component.html
  src/web-app/app/heroes/search/hero-search.component.scss
  src/web-app/app/heroes/search/hero-search.component.spec.ts
  src/web-app/app/heroes/search/hero-search.component.ts
  src/web-app/app/lines/detail/line-detail.component.html
  src/web-app/app/lines/detail/line-detail.component.scss
  src/web-app/app/lines/detail/line-detail.component.ts
  src/web-app/app/lines/line.service.ts
  src/web-app/app/lines/line.ts
  src/web-app/app/lines/lines-routing.module.ts
  src/web-app/app/lines/lines.component.ts
  src/web-app/app/lines/lines.module.ts
  src/web-app/app/lines/list/line-list.component.html
  src/web-app/app/lines/list/line-list.component.scss
  src/web-app/app/lines/list/line-list.component.ts
Labels: Frontend, api, backend, fix

#61 Feature/link front and back
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/arrows/test/arrows.component.spec.ts
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/pins/test/pins.component.spec.ts
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/slide/test/slide.component.spec.ts
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/test/carousel.component.spec.ts
  src/web-app/app/my-octotrails-ng6-carousel/components/test/app.component.spec.ts
  src/web-app/app/my-octotrails-ng6-carousel/directives/test/carouselHandler.spec.ts
  src/web-app/app/my-octotrails-ng6-carousel/services/test/carousel.service.spec.ts
  src/web-app/app/shared/components/message/message.component.spec.ts
  src/web-app/app/shared/services/message.service.spec.ts
  src/web-app/app/stops/categories/categories.component.spec.ts
  src/web-app/app/stops/detail/detail.component.spec.ts
  src/web-app/app/stops/history/history.component.spec.ts
  src/web-app/app/stops/search/search.component.html
  src/web-app/app/stops/search/search.component.spec.ts
  src/web-app/app/stops/search/search.component.ts
  src/web-app/app/stops/stop.ts
  src/web-app/app/stops/stops.module.ts
  src/web-app/app/stops/stops.service.ts
  src/web-app/app/stops/update/update.component.spec.ts
  src/web-app/tsconfig.spec.json
Labels: Frontend, backend

#62 Feature/doc model format
  documentation/api/endpoints/questions/GET_questions.md
  documentation/api/endpoints/stops/GET_proximity.md
  documentation/api/endpoints/stops/GET_search.md
Labels: Documentation

#63 Fix/60-env file
  .env
  .env.example
  .gitignore
  src/web-api/config/config.js
  src/web-app/environments/environment.prod.ts
  src/web-app/environments/environment.ts
Labels: fix

#65 Fixed reference to API_URL in stops service
  src/web-app/app/stops/stops.service.ts
Labels: fix

#69 Feature/56 api post new update
  package-lock.json
  package.json
  src/web-api/config/express.js
  src/web-api/config/param-validation.js
  src/web-api/controllers/inputs.controller.js
  src/web-api/controllers/stops.controller.js
  src/web-api/index.js
  src/web-api/models/history.model.js
  src/web-api/models/input.model.js
  src/web-api/models/question.model.js
  src/web-api/models/seeds/index.js
  src/web-api/models/seeds/inputs.mock.json
  src/web-api/models/seeds/inputs.seed.js
  src/web-api/models/seeds/questions.mock.json
  src/web-api/routes/auth.route.js
  src/web-api/routes/stops.route.js
Labels: api, backend

#74 Fix/correct stib api url
  src/web-api/config/config.js
  src/web-api/controllers/stops.controller.js
Labels: backend

#77 Feature/current user location
  src/web-app/app/map-box/map-box.component.ts
Labels: fix

#78 Feature/current user location
  src/web-app/app/map-box/map-box.component.ts
Labels: fix

#87 Feature/map clusters
  src/web-app/app/map-box/map-box.component.ts
Labels: Frontend

#89 Fix/correct mock
  package-lock.json
  package.json
  src/web-api/routes/stops.route.js
  src/web-app/app/app-routing.module.ts
  src/web-app/app/app.module.ts
  src/web-app/app/data.mock.ts
  src/web-app/app/map-box/map.service.ts
  src/web-app/app/questions/question-types/boolean/boolean.component.css
  src/web-app/app/questions/question-types/boolean/boolean.component.html
  src/web-app/app/questions/question-types/boolean/boolean.component.ts
  src/web-app/app/questions/question-types/multiple/multiple.component.css
  src/web-app/app/questions/question-types/multiple/multiple.component.html
  src/web-app/app/questions/question-types/multiple/multiple.component.ts
  src/web-app/app/questions/question-types/number/number.component.css
  src/web-app/app/questions/question-types/number/number.component.ts
  src/web-app/app/questions/questions.module.ts
  src/web-app/app/shared/mock/questions.mock.ts
  src/web-app/app/stops/detail/detail.component.ts
  src/web-app/app/stops/question-types/boolean/boolean.component.css
  src/web-app/app/stops/question-types/boolean/boolean.component.html
  src/web-app/app/stops/question-types/boolean/boolean.component.spec.ts
  src/web-app/app/stops/question-types/boolean/boolean.component.ts
  src/web-app/app/stops/question-types/number/number.component.css
  src/web-app/app/stops/question-types/number/number.component.html
  src/web-app/app/stops/question-types/number/number.component.spec.ts
  src/web-app/app/stops/question-types/number/number.component.ts
  src/web-app/app/stops/stop.ts
  src/web-app/app/stops/stops-routing.module.ts
  src/web-app/app/stops/stops.module.ts
  src/web-app/app/stops/stops.service.ts
  yarn.lock
Labels: Frontend

#90 Fix/correct mock
  src/web-api/controllers/questions.controller.js
  src/web-app/app/app.module.ts
  src/web-app/app/data.mock.ts
  src/web-app/app/questions/overview/overview.component.ts
  src/web-app/app/stops/detail/detail.component.html
  src/web-app/app/stops/search/search.component.html
Labels: Frontend, backend, fix

#92 Adapt Service to api structure
  src/web-app/app/stops/stops.service.ts
Labels: Frontend

#93 Feature/25 get categories
  src/web-api/controllers/categories.controller.js
  src/web-api/routes/categories.route.js
  src/web-app/app/stops/stops.service.ts
Labels: api, backend

#95 Feature/41 show map on detail page
  package-lock.json
  src/web-app/app/stops/detail/detail.component.ts
  src/web-app/app/stops/location/location.component.css
  src/web-app/app/stops/location/location.component.html
  src/web-app/app/stops/location/location.component.ts
  src/web-app/app/stops/stop.ts
  src/web-app/app/stops/stops-routing.module.ts
Labels: Frontend

#96 Front feature/search styling
  src/web-app/app/stops/search/search.component.html
  src/web-app/app/stops/search/search.component.scss
  src/web-app/app/stops/search/search.component.ts
  src/web-app/styles.scss
Labels: Design, Frontend

#97 Map on detail page is not draggable anymore
  src/web-app/app/stops/location/location.component.ts
Labels: Frontend

#100 Update param-validation.js
  src/web-api/config/param-validation.js
Labels: fix

#102 Feature/18 local storage
  src/web-app/app/questions/overview/overview.component.html
  src/web-app/app/questions/overview/overview.component.ts
  src/web-app/app/questions/question-types/boolean/boolean.component.ts
  src/web-app/app/questions/question-types/multiple/multiple.component.ts
  src/web-app/app/questions/question-types/number/number.component.ts
  src/web-app/app/questions/question-types/string/string.component.ts
  src/web-app/app/questions/questions.service.ts
Labels: Frontend

#104 Fixed search by id
  src/web-app/app/stops/detail/detail.component.ts
  src/web-app/app/stops/stops.service.ts
Labels: fix

#107 Feature/25 get categories
  src/web-api/controllers/categories.controller.js
  src/web-api/models/category.model.js
  src/web-api/models/question.model.js
  src/web-api/models/seeds/categories.mock.json
  src/web-api/models/seeds/categories.seed.js
  src/web-api/models/seeds/histories.seed.js
  src/web-api/models/seeds/index.js
  src/web-api/models/seeds/inputs.seed.js
  src/web-api/models/seeds/questions.mock.json
  src/web-api/models/seeds/questions.seed.js
  src/web-api/routes/categories.route.js
  src/web-api/routes/histories.route.js
  src/web-api/routes/index.route.js
  src/web-api/routes/lines.route.js
  src/web-app/app/app.component.scss
  src/web-app/app/map-box/map-box.component.ts
  src/web-app/app/stops/detail/detail.component.scss
  src/web-app/app/stops/location/location.component.css
  src/web-app/app/stops/location/location.component.ts
  src/web-app/app/stops/search/search.component.html
  src/web-app/app/stops/search/search.component.scss
  src/web-app/app/stops/search/search.component.ts
  src/web-app/styles.scss
Labels: backend

#112 Ajust validation
  src/web-api/config/param-validation.js
Labels: backend, fix

#113 Feature/doc model format
  documentation/api/endpoints/categories/GET_catetgories.md
  documentation/api/endpoints/categories/GET_questions.md
  documentation/api/endpoints/histories/GET_history.md
  documentation/api/endpoints/questions/GET_questions.md
  documentation/api/endpoints/stops/GET_histories.md
  documentation/api/formats.md
  src/web-api/config/config.js
  src/web-api/config/express.js
  src/web-api/config/param-validation.js
  src/web-api/controllers/auth.controller.js
  src/web-api/controllers/categories.controller.js
  src/web-api/controllers/histories.controller.js
  src/web-api/controllers/inputs.controller.js
  src/web-api/controllers/questions.controller.js
  src/web-api/controllers/stops.controller.js
  src/web-api/helpers/APIError.js
  src/web-api/helpers/utils.js
  src/web-api/index.js
  src/web-api/models/category.model.js
  src/web-api/models/history.model.js
  src/web-api/models/input.model.js
  src/web-api/models/question.model.js
  src/web-api/models/seeds/histories.seed.js
  src/web-api/models/seeds/index.js
  src/web-api/models/seeds/inputs.seed.js
  src/web-api/models/seeds/questions.seed.js
  src/web-api/models/stop.model.js
  src/web-api/routes/categories.route.js
  src/web-api/routes/histories.route.js
  src/web-api/routes/index.route.js
  src/web-api/routes/questions.route.js
  src/web-api/routes/stops.route.js
Labels: backend, documentation

#121 Front feature/questions styling
  src/web-app/app/questions/overview/overview.component.css
  src/web-app/app/questions/overview/overview.component.html
  src/web-app/app/questions/overview/overview.component.ts
  src/web-app/app/questions/question-types/boolean/boolean.component.css
  src/web-app/app/questions/question-types/boolean/boolean.component.html
  src/web-app/app/questions/question-types/boolean/boolean.component.ts
  src/web-app/app/questions/question-types/multiple/multiple.component.css
  src/web-app/app/questions/question-types/multiple/multiple.component.html
  src/web-app/app/questions/question-types/multiple/multiple.component.ts
  src/web-app/app/questions/question-types/number/number.component.css
  src/web-app/app/questions/question-types/number/number.component.html
  src/web-app/app/questions/question-types/string/string.component.css
  src/web-app/app/questions/question-types/string/string.component.html
  src/web-app/app/stops/detail/detail.component.html
  src/web-app/app/stops/detail/detail.component.scss
  src/web-app/app/stops/search/search.component.scss
Labels: design, frontend

#124 Changed questions model and mock file
  src/web-api/models/question.model.js
  src/web-api/models/seeds/questions.mock.json
Labels: backend, fix

#126 Update question.model.js
  src/web-api/models/question.model.js
Labels: frontend

#127 Front feature/detail styling
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/arrows/arrows.template.html
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/arrows/assets/arrows.styles.scss
  src/web-app/app/my-octotrails-ng6-carousel/components/carousel/pins/assets/pins.styles.scss
  src/web-app/app/stops/detail/detail.component.html
  src/web-app/app/stops/detail/detail.component.scss
  src/web-app/app/stops/search/search.component.html
  src/web-app/app/stops/search/search.component.scss
  src/web-app/assets/icons/arrow.svg
  src/web-app/assets/icons/history.svg
  src/web-app/assets/icons/locationPin.png
  src/web-app/assets/icons/locationPin.svg
  src/web-app/assets/icons/update.svg
  src/web-app/environments/environment.ts
  src/web-app/index.html
  src/web-app/styles.scss
Labels: design, frontend

#134 Fix/remove frontend environment file
  src/web-app/environments/environment.prod.ts
  src/web-app/environments/environment.ts
Labels: frontend

#135 Update environment.ts
  src/web-app/environments/environment.ts
Labels: fix

#137 Update environment.ts
  src/web-app/environments/environment.ts
Labels: fix

#140 Fix/express public on dev
  src/web-api/config/config.js
  src/web-api/config/express.js
Labels: backend, fix

#143 Added click to open question
  src/web-app/app/shared/components/question-types/boolean/question-type-boolean.component.html
  src/web-app/app/shared/components/question-types/boolean/question-type-boolean.component.ts
  src/web-app/app/shared/components/question-types/multiple/question-type-multiple.component.html
  src/web-app/app/shared/components/question-types/multiple/question-type-multiple.component.ts
  src/web-app/app/shared/components/question-types/number/question-type-number.component.html
  src/web-app/app/shared/components/question-types/number/question-type-number.component.ts
  src/web-app/app/shared/components/question-types/string/question-type-string.component.html
  src/web-app/app/shared/components/question-types/string/question-type-string.component.ts
Labels: frontend

#148 push
  src/web-app/app/stops/detail/stop-detail.component.ts
  src/web-app/app/stops/stop.ts
Labels: fix

#149 Add PWA feature
  angular.json
  package.json
  src/web-app/environments/environment.ts
Labels: backend, fix, frontend

#150 Replace all entrypoint to fix AoT error
  angular.json
  src/web-app/app/app-routing.module.ts
  src/web-app/app/stops/stops-routing.module.ts
Labels: api, backend, bug

#158 Fixed some dutch translations
  src/web-app/assets/i18n/nl.json
Labels: fix
